### PR TITLE
Add refresh same page parameter

### PR DESCRIPTION
**Pull request by NZX-DeSiGN**
Hi, 

I share what I made for my project. I needed to reload the page if the target of clicked link is the same page, so I added a refresh parameter to Ajaxify (with default true). I understand you don't need it for 4nf.org because of the hover navigation, but in my project content of pages can change very quickly and do nothing when the same link is clicked is a problem for me. Tell me what do you think about it !

Thanks,
Nicolas

### CODE REVIEW

**Comment by arvgta** [comment]
Hi Nicolas,

absolutely fabulous!  Of course, very useful in a highly dynamic environment...

Thanks for sharing your findings!

**EDIT:  The only thing worth discussing further is whether to really make it default?**

**Comment by NZX-DeSiGN** [comment]
Hi,

Yes, it's up to you to choose ! I made it default, because for me it's the default behaviour of a non ajaxify website !

**Comment by arvgta** [comment]
Hi,

it should be set to what the [majority of users](http://4nf.org/demos/) expect...
I think the usual are not that dynamic sites?

**Comment by NZX-DeSiGN** [comment]
Hi,

Ok, no problem for me, disable it by default !

**Pull request merged**
